import type { Metadata } from 'next'
import './globals.css'
import Navbar from './components/navbar/Navbar'
import Sidebar from './components/sidebar/sidebar'
import { Providers } from './Providers'
import Footer from './components/footer/Footer'


export const metadata: Metadata = {
  title: 'Next-Daisy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  return (

    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
            <div className="w-full flex-none md:w-64">
              <Sidebar />
            </div>
            <div className="flex-grow md:overflow-y-auto">
            <Navbar />
              {children}
              </div>
            {/* <div className="flex-1">

              <main>
                <header>
                  <Navbar />
                </header>
                {children}
              </main>

            </div>
            <footer>
              <Footer />
            </footer> */}
          </div>
        </Providers>
      </body>
    </html>

  )
}
